services:
  kafka:
    image: confluentinc/cp-kafka:7.5.16
    container_name: kafka
    ports:
      - "${KAFKA_PORT:-9092}:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:29093'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      CLUSTER_ID: 'MkU3OEVBNTcwNTJENDM2Qk'
      
      KAFKA_LISTENERS: 'PLAINTEXT://kafka:29092,CONTROLLER://kafka:29093,PLAINTEXT_HOST://0.0.0.0:9092'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:${KAFKA_PORT:-9092}'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  jobmanager:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flink-jobmanager
    ports:
      - "${FLINK_UI_PORT:-8081}:8081"
    command: jobmanager
    volumes:
      - ./flink-job:/app
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager

  taskmanager:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flink-taskmanager
    depends_on:
      - jobmanager
    command: taskmanager
    volumes:
      - ./flink-job:/app
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: ${FLINK_TASK_SLOTS:-2}

  publisher:
    build:
      context: ./publisher
      dockerfile: Dockerfile
    container_name: golang-publisher
    depends_on:
      - kafka
    environment:
      - KAFKA_BROKER=kafka:29092

  subscriber:
    build:
      context: ./subscriber
      dockerfile: Dockerfile
    container_name: golang-subscriber
    depends_on:
      - kafka
    environment:
      - KAFKA_BROKER=kafka:29092